set -g mouse on

# indexing windows and panes from 1
set -g base-index 1
set -g pane-base-index 1

set -g default-shell $SHELL

# kill session with prefix + q confirmation
bind q confirm-before -p "Kill session #S? (y/n)" kill-session

set -g status-style "bg=#1D1E29,fg=white"
set -g pane-active-border-style "fg=#89B4F4"

# binding keys to moving between panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
