# Preload the image(s) into memory
preload = /home/szbence/.config/hypr/kereszt.jpg

# Set the wallpaper for specific monitors
# Use 'wallpaper = ,/path/to/image.jpg' to apply to ALL monitors
wallpaper = , /home/szbence/.config/hypr/kereszt.jpg
# Enable splash text (the text at the bottom)
splash = false

# Fully disable IPC (Inter-process Communication) for better battery/performance
# ipc = off
