# See https://wiki.hypr.land/Configuring/Monitors/
$mainMod = SUPER # Sets "Windows" key as main modifier

$terminal = kitty
$fileManager = dolphin
$browser = firefox
$menu = wofi --show drun

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

exec-once = dunst
exec-once = waybar
exec-once = hyprpm reload -n
exec-once = nm-applet
exec-once = blueman-applet
exec-once = /home/szbence/.config/hypr/tablet-mode.sh
exec-once = wvkbd-mobintl --hidden -L 200 -H 350
exec-once = nwg-drawer -r
exec-once = hypridle
# exec-once = sleep 5; wpaperd -d ;dunstify "Hyprland" "Welcome back, szbence!" 
exec-once = hyprpaper
exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE

source = ~/.config/hypr/monitor.conf

source = ~/.config/hypr/decoration.conf

source = ~/.config/hypr/input.conf

source = ~/.config/hypr/shortcuts.conf

source = ~/.config/hypr/windowrules.conf
