
monitor=eDP-1,1366x768@60,auto,1, transform, 0
#transform touch screen too
input:touchdevice:transform = 0

input:tablet:transform = 0

#rotate the screen 90 degrees clockwise
bind = $mainMod SHIFT, i, exec, hyprctl --batch "keyword monitor eDP-1,1366x768@60,auto,1,transform,1; keyword input:touchdevice:transform 1; keyword input:tablet:transform 1" 
#only monitor
bind = $mainMod SHIFT, t, exec, hyprctl keyword monitor eDP-1,1366x768@60,auto,1,transform,1
bind = $mainMod SHIFT, r, exec, hyprctl reload
