windowrulev2 = workspace 2, class:^(org.mozilla.firefox)$

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = size 500 400, class:^(blueman-manager)$
windowrulev2 = move 830 300, class:^(blueman-manager)$

windowrulev2 = float, class:^(btop)$
windowrulev2 = size 700 600, class:^(btop)$
windowrulev2 = move 630 50, class:^(btop)$


windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = size 398 224, title:^(Picture-in-Picture)$
windowrulev2 = move 30 30, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = opacity 1 override, title:^(Picture-in-Picture)$

windowrule = opacity 1.0 0.9 override, class:^(kitty)$
# windowrule = keep_aspect_ratio , title:^(Picture-in-Picture)$


